eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
microservice:
  ORDERS:
    endpoints:
      endpoint:
        uri: http://ORDERS/Order/place-order
        
  PAYMENT:
    endpoints:
      endpoint:
        uri: http://PAYMENT/payment/dopayment  
